using System.Collections.Generic;
using System.Linq;

namespace ScenarioGenerator.Solutions
{
    // https://github.com/OrchardCMS/OrchardCore
    // Total Projects: 127
    // Total ProjectRefs: 529
    // Total PackageRefs: 237
    // Unique PackageRefs: 84

    class OrchardCoreSolution : ISolution
    {
        public IList<(string Name, IEnumerable<string> ProjectReferences, IEnumerable<(string Name, string Version)> PackageReferences)> Projects { get; } =
            new List<(string Name, IEnumerable<string> ProjectReferences, IEnumerable<(string Name, string Version)> PackageReferences)>
        {
            // Rank 0
            ( "OrchardCore.Application.Targets", Enumerable.Empty<string>(), Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.BackgroundTasks.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("System.ComponentModel" ,"4.3.0"), } ),
            ( "OrchardCore.Data.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("YesSql.Core" ,"$(YesSqlVersion)"), } ),
            ( "OrchardCore.DeferredTasks.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("System.ComponentModel" ,"4.3.0"), } ),
            ( "OrchardCore.Entities", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Newtonsoft.Json" ,"$(NewtonsoftJsonVersion)"), } ),
            ( "OrchardCore.Environment.Cache.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.Primitives" ,"$(MicrosoftExtensionsPrimitivesPackageVersion)"), } ),
            ( "OrchardCore.Environment.Extensions.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"$(MicrosoftExtensionsHostingAbstractionsPackageVersion)"), ("Microsoft.Extensions.FileProviders.Abstractions" ,"$(MicrosoftExtensionsFileProvidersAbstractionsPackageVersion)"), ("Microsoft.Extensions.Logging.Abstractions" ,"$(MicrosoftExtensionsLoggingAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.FileStorage.Abstractions", Enumerable.Empty<string>(), Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Liquid.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Fluid.Core" ,"$(FluidCoreVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), ("Microsoft.Extensions.Options" ,"$(MicrosoftExtensionsOptionsPackageVersion)"), } ),
            ( "OrchardCore.Localization.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Localization" ,"$(MicrosoftAspNetCoreMvcLocalizationPackageVersion)"), ("Microsoft.Extensions.Caching.Abstractions" ,"$(MicrosoftExtensionsCachingAbstractionsPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Lucene.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Lucene.Net" ,"4.8.0-beta00004"), } ),
            ( "OrchardCore.Modules.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Routing" ,"$(MicrosoftAspNetCoreRoutingPackageVersion)"), ("Microsoft.Extensions.Configuration.Abstractions" ,"$(MicrosoftExtensionsConfigurationAbstractionsPackageVersion)"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Parser.Yaml", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration" ,"$(MicrosoftExtensionsConfigurationPackageVersion)"), ("Microsoft.Extensions.Configuration.FileExtensions" ,"$(MicrosoftExtensionsConfigurationFileExtensionsPackageVersion)"), ("YamlDotNet" ,"4.2.1"), } ),
            ( "OrchardCore.Queries.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Newtonsoft.Json" ,"$(NewtonsoftJsonVersion)"), } ),
            ( "OrchardCore.Recipes.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Microsoft.Extensions.FileProviders.Abstractions" ,"$(MicrosoftExtensionsFileProvidersAbstractionsPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), ("Microsoft.Extensions.Logging.Abstractions" ,"$(MicrosoftExtensionsLoggingAbstractionsPackageVersion)"), ("Microsoft.Extensions.Options" ,"$(MicrosoftExtensionsOptionsPackageVersion)"), ("Newtonsoft.Json" ,"$(NewtonsoftJsonVersion)"), } ),
            ( "OrchardCore.ResourceManagement.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"$(MicrosoftAspNetCoreMvcViewFeaturesPackageVersion)"), ("Microsoft.AspNetCore.Razor.Runtime" ,"$(MicrosoftAspNetCoreRazorRuntimePackageVersion)"), } ),
            ( "OrchardCore.Scripting.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Security.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"$(MicrosoftAspNetCoreIdentityPackageVersion)"), } ),
            ( "OrchardCore.Setup.Abstractions", Enumerable.Empty<string>(), Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.XmlRpc.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Core" ,"$(MicrosoftAspNetCoreMvcCorePackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),

            // Rank 1
            ( "OrchardCore.Admin.Abstractions", new string[] { "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Security.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Abstractions" ,"$(MicrosoftAspNetCoreMvcAbstractionsPackageVersion)"), ("Microsoft.AspNetCore.Mvc.Core" ,"$(MicrosoftAspNetCoreMvcCorePackageVersion)"), } ),
            ( "OrchardCore.Environment.Shell.Abstractions", new string[] { "OrchardCore.Environment.Extensions.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration" ,"$(MicrosoftExtensionsConfigurationPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), ("Microsoft.Extensions.Logging.Abstractions" ,"$(MicrosoftExtensionsLoggingAbstractionsPackageVersion)"), ("Newtonsoft.Json" ,"$(NewtonsoftJsonVersion)"), } ),
            ( "OrchardCore.FileStorage.AzureBlob", new string[] { "OrchardCore.FileStorage.Abstractions", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("WindowsAzure.Storage" ,"8.5.0"), } ),
            ( "OrchardCore.FileStorage.FileSystem", new string[] { "OrchardCore.FileStorage.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.FileProviders.Physical" ,"2.0.0"), } ),
            ( "OrchardCore.Localization.Core", new string[] { "OrchardCore.Localization.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"$(MicrosoftExtensionsHostingAbstractionsPackageVersion)"), ("Microsoft.Extensions.Caching.Abstractions" ,"$(MicrosoftExtensionsCachingAbstractionsPackageVersion)"), ("Microsoft.Extensions.Localization" ,"$(MicrosoftExtensionsLocalizationPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Lucene.Core", new string[] { "OrchardCore.Lucene.Abstractions", "OrchardCore.Queries.Abstractions", }, new (string Name, string Version)[] { ("Lucene.Net.QueryParser" ,"4.8.0-beta00004"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Newtonsoft.Json" ,"$(NewtonsoftJsonVersion)"), } ),
            ( "OrchardCore.Module.Targets", new string[] { "OrchardCore.Modules.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Mvc.Abstractions", new string[] { "OrchardCore.Entities", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Core" ,"$(MicrosoftAspNetCoreMvcCorePackageVersion)"), ("Microsoft.AspNetCore.Mvc.Razor" ,"$(MicrosoftAspNetCoreMvcRazorPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.ResourceManagement", new string[] { "OrchardCore.ResourceManagement.Abstractions", }, new (string Name, string Version)[] { ("System.Collections.Specialized" ,"4.3.0"), } ),
            ( "OrchardCore.Scripting.Core", new string[] { "OrchardCore.Scripting.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Scripting.JavaScript", new string[] { "OrchardCore.Scripting.Abstractions", }, new (string Name, string Version)[] { ("Jint" ,"2.11.10"), ("Microsoft.Extensions.Caching.Abstractions" ,"$(MicrosoftExtensionsCachingAbstractionsPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Users.Abstractions", new string[] { "OrchardCore.Security.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),

            // Rank 2
            ( "OrchardCore.BackgroundTasks", new string[] { "OrchardCore.BackgroundTasks.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"$(MicrosoftExtensionsHostingAbstractionsPackageVersion)"), ("Microsoft.Extensions.Logging.Abstractions" ,"$(MicrosoftExtensionsLoggingAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.DeferredTasks", new string[] { "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Environment.Shell.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Http.Abstractions" ,"$(MicrosoftAspNetCoreHttpAbstractionsPackageVersion)"), ("Microsoft.Extensions.Logging.Abstractions" ,"$(MicrosoftExtensionsLoggingAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Diagnostics.Elm", new string[] { "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Diagnostics.Elm" ,"$(MicrosoftAspNetCoreDiagnosticsElmPackageVersion)"), } ),
            ( "OrchardCore.Environment.Commands", new string[] { "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Environment.Extensions", new string[] { "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Parser.Yaml", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Caching.Abstractions" ,"$(MicrosoftExtensionsCachingAbstractionsPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), ("Microsoft.Extensions.Options" ,"$(MicrosoftExtensionsOptionsPackageVersion)"), ("System.Threading.Tasks.Parallel" ,"4.3.0"), } ),
            ( "OrchardCore.Environment.Shell", new string[] { "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Parser.Yaml", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Abstractions" ,"$(MicrosoftExtensionsConfigurationAbstractionsPackageVersion)"), ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), ("Microsoft.Extensions.Configuration.Xml" ,"$(MicrosoftExtensionsConfigurationXmlPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), ("Microsoft.Extensions.Logging.Abstractions" ,"$(MicrosoftExtensionsLoggingAbstractionsPackageVersion)"), ("Microsoft.Extensions.Options" ,"$(MicrosoftExtensionsOptionsPackageVersion)"), ("System.Threading.Tasks.Parallel" ,"4.3.0"), } ),
            ( "OrchardCore.Feeds.Abstractions", new string[] { "OrchardCore.Mvc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Abstractions" ,"$(MicrosoftAspNetCoreMvcAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.HomeRoute", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Logging.NLog", new string[] { "OrchardCore.Environment.Shell.Abstractions", }, new (string Name, string Version)[] { ("NLog.Web.AspNetCore" ,"4.4.1"), ("System.Security.AccessControl" ,"4.4.0"), } ),
            ( "OrchardCore.Mvc.Core", new string[] { "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Mvc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"$(MicrosoftAspNetCoreMvcPackageVersion)"), ("Microsoft.AspNetCore.Routing" ,"$(MicrosoftAspNetCoreRoutingPackageVersion)"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Microsoft.Extensions.FileProviders.Abstractions" ,"$(MicrosoftExtensionsFileProvidersAbstractionsPackageVersion)"), ("Microsoft.Extensions.FileProviders.Physical" ,"$(MicrosoftExtensionsFileProvidersPhysicalPackageVersion)"), ("Microsoft.Extensions.Logging.Abstractions" ,"$(MicrosoftExtensionsLoggingAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Recipes.Implementations", new string[] { "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Scripting.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"$(MicrosoftExtensionsHostingAbstractionsPackageVersion)"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Microsoft.Extensions.FileSystemGlobbing" ,"$(MicrosoftExtensionsFileSystemGlobbingPackageVersion)"), } ),
            ( "OrchardCore.ResponseCache", new string[] { "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.ResponseCaching" ,"$(MicrosoftAspNetCoreResponseCachingPackageVersion)"), } ),
            ( "OrchardCore.Security", new string[] { "OrchardCore.Mvc.Abstractions", "OrchardCore.Security.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Authorization" ,"$(MicrosoftAspNetCoreAuthorizationPackageVersion)"), } ),
            ( "OrchardCore.Theme.Targets", new string[] { "OrchardCore.Module.Targets", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Users.Core", new string[] { "OrchardCore.Entities", "OrchardCore.Security.Abstractions", "OrchardCore.Users.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"$(MicrosoftAspNetCoreIdentityPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), ("YesSql.Core" ,"$(YesSqlVersion)"), } ),
            ( "OrchardCore.XmlRpc", new string[] { "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.XmlRpc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Formatters.Xml" ,"$(MicrosoftAspNetCoreMvcFormattersXmlPackageVersion)"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"$(MicrosoftAspNetCoreMvcViewFeaturesPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),

            // Rank 3
            ( "OrchardCore.ContentManagement.Abstractions", new string[] { "OrchardCore.Mvc.Core", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Html.Abstractions" ,"$(MicrosoftAspNetCoreHtmlAbstractionsPackageVersion)"), ("Microsoft.AspNetCore.Routing.Abstractions" ,"$(MicrosoftAspNetCoreRoutingAbstractionsPackageVersion)"), ("Newtonsoft.Json" ,"$(NewtonsoftJsonVersion)"), } ),
            ( "OrchardCore.Data", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Microsoft.Extensions.Logging.Abstractions" ,"$(MicrosoftExtensionsLoggingAbstractionsPackageVersion)"), ("Newtonsoft.Json" ,"$(NewtonsoftJsonVersion)"), ("YesSql.Provider.MySql" ,"$(YesSqlProvidersVersion)"), ("YesSql.Provider.PostgreSql" ,"$(YesSqlProvidersVersion)"), ("YesSql.Provider.SqLite" ,"$(YesSqlProvidersVersion)"), ("YesSql.Provider.SqlServer" ,"$(YesSqlProvidersVersion)"), } ),
            ( "OrchardCore.DisplayManagement", new string[] { "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Mvc.Core", }, new (string Name, string Version)[] { ("Castle.Core" ,"4.1.1"), ("Microsoft.AspNetCore.Html.Abstractions" ,"$(MicrosoftAspNetCoreHtmlAbstractionsPackageVersion)"), ("Microsoft.AspNetCore.Mvc.Localization" ,"$(MicrosoftAspNetCoreMvcLocalizationPackageVersion)"), ("Microsoft.Extensions.Logging.Abstractions" ,"$(MicrosoftExtensionsLoggingAbstractionsPackageVersion)"), ("System.Diagnostics.TraceSource" ,"4.3.0"), ("System.Reflection.Extensions" ,"4.3.0"), } ),
            ( "OrchardCore.Environment.Navigation", new string[] { "OrchardCore.Environment.Shell", "OrchardCore.Security", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Core" ,"$(MicrosoftAspNetCoreMvcCorePackageVersion)"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"$(MicrosoftAspNetCoreMvcViewFeaturesPackageVersion)"), ("Microsoft.AspNetCore.Routing" ,"$(MicrosoftAspNetCoreRoutingPackageVersion)"), } ),
            ( "OrchardCore.Environment.Shell.Data", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Shell", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Feeds.Core", new string[] { "OrchardCore.Feeds.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Hosting.Console", new string[] { "OrchardCore.Environment.Commands", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting" ,"$(MicrosoftAspNetCoreHostingPackageVersion)"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Modules", new string[] { "OrchardCore.Environment.Extensions", "OrchardCore.Environment.Shell", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"$(MicrosoftExtensionsHostingAbstractionsPackageVersion)"), ("Microsoft.AspNetCore.Http" ,"$(MicrosoftAspNetCoreHttpPackageVersion)"), ("Microsoft.AspNetCore.StaticFiles" ,"$(MicrosoftAspNetCoreStaticFilesPackageVersion)"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Microsoft.Extensions.FileProviders.Composite" ,"$(MicrosoftExtensionsFileProvidersCompositePackageVersion)"), ("Microsoft.Extensions.Localization" ,"$(MicrosoftExtensionsLocalizationPackageVersion)"), ("Microsoft.Extensions.Logging" ,"$(MicrosoftExtensionsLoggingPackageVersion)"), } ),
            ( "OrchardCore.Mvc.HelloWorld", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Mvc.Core", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Scripting", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Mvc.Core", "OrchardCore.Scripting.Core", "OrchardCore.Scripting.JavaScript", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),

            // Rank 4
            ( "OrchardCore.ContentManagement", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Html.Abstractions" ,"$(MicrosoftAspNetCoreHtmlAbstractionsPackageVersion)"), ("Microsoft.AspNetCore.Mvc.DataAnnotations" ,"$(MicrosoftAspNetCoreMvcDataAnnotationsPackageVersion)"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"$(MicrosoftAspNetCoreMvcViewFeaturesPackageVersion)"), ("Microsoft.Extensions.Caching.Abstractions" ,"$(MicrosoftExtensionsCachingAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.ContentManagement.Display", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.DisplayManagement", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Deployment.Abstractions", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Recipes.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Diagnostics", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Diagnostics" ,"$(MicrosoftAspNetCoreDiagnosticsPackageVersion)"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"$(MicrosoftAspNetCoreMvcViewFeaturesPackageVersion)"), ("Microsoft.AspNetCore.StaticFiles" ,"$(MicrosoftAspNetCoreStaticFilesPackageVersion)"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.DisplayManagement.Liquid", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Liquid.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Entities.DisplayManagement", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Entities", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Environment.Cache", new string[] { "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Modules", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Http.Abstractions" ,"$(MicrosoftAspNetCoreHttpAbstractionsPackageVersion)"), ("Microsoft.Extensions.Caching.Abstractions" ,"$(MicrosoftExtensionsCachingAbstractionsPackageVersion)"), ("Microsoft.Extensions.Caching.Memory" ,"$(MicrosoftExtensionsCachingMemoryPackageVersion)"), } ),
            ( "OrchardCore.Feeds", new string[] { "OrchardCore.Feeds.Core", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Abstractions" ,"$(MicrosoftAspNetCoreMvcAbstractionsPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Indexing.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Media.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.FileStorage.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Menu.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.MetaWeblog.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.XmlRpc.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Mvc", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Modules", "OrchardCore.Mvc.Core", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Nancy.Core", new string[] { "OrchardCore.Modules", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Owin" ,"$(MicrosoftAspNetCoreOwinPackageVersion)"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Nancy" ,"2.0.0-clinteastwood"), } ),
            ( "OrchardCore.Navigation", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Security", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Roles", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Security.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"$(MicrosoftAspNetCoreIdentityPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Settings", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities", "OrchardCore.Environment.Navigation", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Setup.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"$(MicrosoftAspNetCoreMvcPackageVersion)"), ("Microsoft.Extensions.Caching.Abstractions" ,"$(MicrosoftExtensionsCachingAbstractionsPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Setup", new string[] { "OrchardCore.Data", "OrchardCore.DisplayManagement", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Setup.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"$(MicrosoftAspNetCoreIdentityPackageVersion)"), } ),
            ( "OrchardCore.Tenants", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.StaticFiles" ,"$(MicrosoftAspNetCoreStaticFilesPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "SafeMode", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"$(MicrosoftAspNetCoreMvcPackageVersion)"), ("Microsoft.AspNetCore.Mvc.TagHelpers" ,"$(MicrosoftAspNetCoreMvcTagHelpersPackageVersion)"), } ),
            ( "TheAdmin", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"$(MicrosoftAspNetCoreMvcPackageVersion)"), ("Microsoft.AspNetCore.Mvc.TagHelpers" ,"$(MicrosoftAspNetCoreMvcTagHelpersPackageVersion)"), } ),
            ( "TheAgencyTheme", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"$(MicrosoftAspNetCoreMvcPackageVersion)"), ("Microsoft.AspNetCore.Mvc.TagHelpers" ,"$(MicrosoftAspNetCoreMvcTagHelpersPackageVersion)"), } ),

            // Rank 5
            ( "OrchardCore.Admin", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Settings", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Application.Mvc.Targets", new string[] { "OrchardCore.Application.Targets", "OrchardCore.Mvc", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Commons", new string[] { "OrchardCore.BackgroundTasks", "OrchardCore.Data", "OrchardCore.DeferredTasks", "OrchardCore.DisplayManagement", "OrchardCore.DisplayManagement.Liquid", "OrchardCore.Environment.Cache", "OrchardCore.Environment.Extensions", "OrchardCore.Environment.Shell.Data", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.ContentPreview", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Module.Targets", "OrchardCore.Security", "OrchardCore.Settings", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.ContentTypes.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.Deployment.Core", new string[] { "OrchardCore.Deployment.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.DynamicCache", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Core", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.Features", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Deployment.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.ResourceManagement.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Layers", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Scripting.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Media.Services", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Media.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Menu", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Nancy", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Nancy.Core", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Nancy.HelloWorld", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Nancy.Core", }, new (string Name, string Version)[] { ("Nancy" ,"2.0.0-clinteastwood"), } ),
            ( "OrchardCore.Resources", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.Themes", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Settings", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.Title", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Security.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Users", new string[] { "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Commands", "OrchardCore.Environment.Navigation", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Setup.Abstractions", "OrchardCore.Users.Core", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"$(MicrosoftAspNetCoreIdentityPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "TheBlogTheme", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.ResourceManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"$(MicrosoftAspNetCoreMvcPackageVersion)"), ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "TheTheme", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.ResourceManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"$(MicrosoftAspNetCoreMvcPackageVersion)"), ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),

            // Rank 6
            ( "OrchardCore.Alias", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Application.Nancy.Targets", new string[] { "OrchardCore.Application.Targets", "OrchardCore.Nancy", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Autoroute", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Security", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Body", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.ContentFields", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"$(MicrosoftAspNetCoreMvcPackageVersion)"), ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.Contents", new string[] { "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Feeds.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Navigation", "OrchardCore.Recipes.Abstractions", "OrchardCore.Scripting.Abstractions", "OrchardCore.Settings", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.ContentTypes", new string[] { "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Deployment.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.CustomSettings", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Deployment", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement", "OrchardCore.Data.Abstractions", "OrchardCore.Deployment.Core", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), ("System.IO.Compression.ZipFile" ,"4.3.0"), } ),
            ( "OrchardCore.Deployment.Remote", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Deployment.Core", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Flows", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.ResourceManagement.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Indexing", new string[] { "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Liquid", new string[] { "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data", "OrchardCore.DisplayManagement", "OrchardCore.DisplayManagement.Liquid", "OrchardCore.Indexing.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Fluid.Core" ,"$(FluidCoreVersion)"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), } ),
            ( "OrchardCore.Localization", new string[] { "OrchardCore.Environment.Shell", "OrchardCore.Features", "OrchardCore.Localization.Abstractions", "OrchardCore.Localization.Core", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Localization" ,"$(MicrosoftAspNetCoreMvcLocalizationPackageVersion)"), } ),
            ( "OrchardCore.Lucene", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.BackgroundTasks.Abstractions", "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Lucene.Core", "OrchardCore.Module.Targets", "OrchardCore.Security", }, new (string Name, string Version)[] { ("Lucene.Net.Analysis.Common" ,"4.8.0-beta00004"), ("Lucene.Net.QueryParser" ,"4.8.0-beta00004"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Markdown", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Markdig" ,"0.13.1"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),
            ( "OrchardCore.Media", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell", "OrchardCore.FileStorage.FileSystem", "OrchardCore.Liquid.Abstractions", "OrchardCore.Media.Abstractions", "OrchardCore.Media.Services", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Security", "OrchardCore.Security.Abstractions", "OrchardCore.XmlRpc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.TagHelpers" ,"$(MicrosoftAspNetCoreMvcTagHelpersPackageVersion)"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"$(MicrosoftAspNetCoreMvcViewFeaturesPackageVersion)"), ("Microsoft.AspNetCore.StaticFiles" ,"$(MicrosoftAspNetCoreStaticFilesPackageVersion)"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), ("MimeMapping" ,"1.0.1.10"), ("OrchardCore.ImageSharp.Web" ,"1.0.0-ci0027"), } ),
            ( "OrchardCore.Mvc.Web", new string[] { "OrchardCore.Application.Mvc.Targets", "OrchardCore.Diagnostics.Elm", "OrchardCore.Hosting.Console", "OrchardCore.Mvc.HelloWorld", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore" ,"$(MicrosoftAspNetCorePackageVersion)"), ("Microsoft.AspNetCore.Diagnostics" ,"$(MicrosoftAspNetCoreDiagnosticsPackageVersion)"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"$(MicrosoftAspNetCoreMvcViewFeaturesPackageVersion)"), ("Microsoft.AspNetCore.Server.IISIntegration" ,"$(MicrosoftAspNetCoreServerIISIntegrationPackageVersion)"), ("Microsoft.AspNetCore.Server.Kestrel" ,"$(MicrosoftAspNetCoreServerKestrelCorePackageVersion)"), ("Microsoft.AspNetCore.StaticFiles" ,"$(MicrosoftAspNetCoreStaticFilesPackageVersion)"), ("Microsoft.Extensions.Localization.Abstractions" ,"$(MicrosoftExtensionsLocalizationAbstractionsPackageVersion)"), ("Microsoft.Extensions.Logging.Console" ,"$(MicrosoftExtensionsLoggingConsolePackageVersion)"), ("System.Collections.Specialized" ,"4.3.0"), ("System.Dynamic.Runtime" ,"4.3.0"), ("System.Linq" ,"4.3.0"), } ),
            ( "OrchardCore.OpenId", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Roles", "OrchardCore.Settings", "OrchardCore.Users", }, new (string Name, string Version)[] { ("AspNet.Security.OAuth.Validation" ,"2.0.0-rc1-0286"), ("Microsoft.AspNetCore.Authentication.JwtBearer" ,"$(MicrosoftAspNetCoreAuthenticationJwtBearerPackageVersion)"), ("OpenIddict" ,"2.0.0-preview1-0657"), } ),
            ( "OrchardCore.Recipes", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Commands", "OrchardCore.Features", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Implementations", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Templates", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.DisplayManagement.Liquid", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Microsoft.Extensions.Localization" ,"$(MicrosoftExtensionsLocalizationPackageVersion)"), } ),
            ( "OrchardCore.Widgets", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),

            // Rank 7
            ( "OrchardCore.Demo", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.BackgroundTasks.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Contents", "OrchardCore.Data.Abstractions", "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Commands", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement", "OrchardCore.ResourceManagement.Abstractions", "OrchardCore.Users.Core", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.Lists", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Contents", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Media.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.ResourceManagement.Abstractions", "OrchardCore.Users.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"$(MicrosoftExtensionsConfigurationJsonPackageVersion)"), } ),
            ( "OrchardCore.Media.Azure", new string[] { "OrchardCore.Admin", "OrchardCore.FileStorage.AzureBlob", "OrchardCore.Media", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Nancy.Web", new string[] { "OrchardCore.Application.Nancy.Targets", "OrchardCore.Nancy.HelloWorld", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore" ,"$(MicrosoftAspNetCorePackageVersion)"), ("Microsoft.AspNetCore.Diagnostics" ,"$(MicrosoftAspNetCoreDiagnosticsPackageVersion)"), ("Microsoft.AspNetCore.Server.IISIntegration" ,"$(MicrosoftAspNetCoreServerIISIntegrationPackageVersion)"), ("Microsoft.AspNetCore.Server.Kestrel" ,"$(MicrosoftAspNetCoreServerKestrelCorePackageVersion)"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"$(MicrosoftExtensionsDependencyInjectionAbstractionsPackageVersion)"), ("Microsoft.Extensions.Logging.Console" ,"$(MicrosoftExtensionsLoggingConsolePackageVersion)"), ("System.Collections.Specialized" ,"4.3.0"), ("System.Dynamic.Runtime" ,"4.3.0"), ("System.Linq" ,"4.3.0"), } ),
            ( "OrchardCore.Queries", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Liquid.Abstractions", "OrchardCore.Lucene", "OrchardCore.Module.Targets", "OrchardCore.Queries.Abstractions", }, new (string Name, string Version)[] { ("Irony.Core" ,"1.0.7"), ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), } ),

            // Rank 8
            ( "OrchardCore.Application.Cms.Targets", new string[] { "OrchardCore.Admin", "OrchardCore.Alias", "OrchardCore.Application.Targets", "OrchardCore.Autoroute", "OrchardCore.Body", "OrchardCore.Commons", "OrchardCore.ContentFields", "OrchardCore.ContentPreview", "OrchardCore.Contents", "OrchardCore.ContentTypes", "OrchardCore.CustomSettings", "OrchardCore.Deployment", "OrchardCore.Deployment.Remote", "OrchardCore.Diagnostics", "OrchardCore.DynamicCache", "OrchardCore.Features", "OrchardCore.Feeds", "OrchardCore.Flows", "OrchardCore.HomeRoute", "OrchardCore.Indexing", "OrchardCore.Layers", "OrchardCore.Liquid", "OrchardCore.Lists", "OrchardCore.Localization", "OrchardCore.Lucene", "OrchardCore.Markdown", "OrchardCore.Media", "OrchardCore.Media.Azure", "OrchardCore.Menu", "OrchardCore.Mvc", "OrchardCore.Navigation", "OrchardCore.Queries", "OrchardCore.Recipes", "OrchardCore.Resources", "OrchardCore.ResponseCache", "OrchardCore.Roles", "OrchardCore.Scripting", "OrchardCore.Settings", "OrchardCore.Setup", "OrchardCore.Templates", "OrchardCore.Tenants", "OrchardCore.Themes", "OrchardCore.Title", "OrchardCore.Users", "OrchardCore.Widgets", "OrchardCore.XmlRpc", "SafeMode", "TheAdmin", "TheAgencyTheme", "TheBlogTheme", "TheTheme", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Tests", new string[] { "OrchardCore.ContentManagement", "OrchardCore.Data", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Extensions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell", "OrchardCore.Hosting.Console", "OrchardCore.Liquid", "OrchardCore.Localization.Abstractions", "OrchardCore.Localization.Core", "OrchardCore.Parser.Yaml", "OrchardCore.Queries", "OrchardCore.Recipes.Implementations", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"$(MicrosoftExtensionsDependencyInjectionPackageVersion)"), ("Microsoft.NET.Test.Sdk" ,"$(TestSdkVersion)"), ("Moq" ,"4.7.99"), ("xunit" ,"$(XunitVersion)"), ("xunit.analyzers" ,"$(XunitAnalyzers)"), ("xunit.runner.visualstudio" ,"$(XunitRunnerVisualStudioVersion)"), } ),

            // Rank 9
            ( "OrchardCore.Cms.Web", new string[] { "OrchardCore.Application.Cms.Targets", "OrchardCore.Hosting.Console", "OrchardCore.Logging.NLog", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore" ,"$(MicrosoftAspNetCorePackageVersion)"), ("Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" ,"$(MicrosoftAspNetCoreMvcRazorViewCompilationPackageVersion)"), } ),
        };

        public string MainProject => "OrchardCore.Cms.Web";
    }
}
