using System.Collections.Generic;
using System.Linq;

namespace ScenarioGenerator.Solutions
{
    // https://github.com/OrchardCMS/OrchardCore
    // Total Projects: 127
    // Total ProjectRefs: 529
    // Total PackageRefs: 237
    // Unique PackageRefs: 84

    class OrchardCoreSolution : ISolution
    {
        public IList<(string Name, IEnumerable<string> ProjectReferences, IEnumerable<string> PackageReferences)> Projects { get; } =
            new List<(string Name, IEnumerable<string> ProjectReferences, IEnumerable<string> PackageReferences)>
        {
            // Rank 0
            ( "OrchardCore.Application.Targets", Enumerable.Empty<string>(), Enumerable.Empty<string>() ),
            ( "OrchardCore.BackgroundTasks.Abstractions", Enumerable.Empty<string>(), new string[] { "System.ComponentModel", } ),
            ( "OrchardCore.Data.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.Extensions.DependencyInjection.Abstractions", "YesSql.Core", } ),
            ( "OrchardCore.DeferredTasks.Abstractions", Enumerable.Empty<string>(), new string[] { "System.ComponentModel", } ),
            ( "OrchardCore.Entities", Enumerable.Empty<string>(), new string[] { "Newtonsoft.Json", } ),
            ( "OrchardCore.Environment.Cache.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.Extensions.Primitives", } ),
            ( "OrchardCore.Environment.Extensions.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.AspNetCore.Hosting.Abstractions", "Microsoft.Extensions.FileProviders.Abstractions", "Microsoft.Extensions.Logging.Abstractions", } ),
            ( "OrchardCore.FileStorage.Abstractions", Enumerable.Empty<string>(), Enumerable.Empty<string>() ),
            ( "OrchardCore.Liquid.Abstractions", Enumerable.Empty<string>(), new string[] { "Fluid.Core", "Microsoft.Extensions.DependencyInjection", "Microsoft.Extensions.Options", } ),
            ( "OrchardCore.Localization.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.AspNetCore.Mvc.Localization", "Microsoft.Extensions.Caching.Abstractions", "Microsoft.Extensions.Localization.Abstractions", } ),
            ( "OrchardCore.Lucene.Abstractions", Enumerable.Empty<string>(), new string[] { "Lucene.Net", } ),
            ( "OrchardCore.Modules.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.AspNetCore.Routing", "Microsoft.Extensions.Configuration.Abstractions", "Microsoft.Extensions.DependencyInjection.Abstractions", "Microsoft.Extensions.Localization.Abstractions", } ),
            ( "OrchardCore.Parser.Yaml", Enumerable.Empty<string>(), new string[] { "Microsoft.Extensions.Configuration", "Microsoft.Extensions.Configuration.FileExtensions", "YamlDotNet", } ),
            ( "OrchardCore.Queries.Abstractions", Enumerable.Empty<string>(), new string[] { "Newtonsoft.Json", } ),
            ( "OrchardCore.Recipes.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.Extensions.DependencyInjection.Abstractions", "Microsoft.Extensions.FileProviders.Abstractions", "Microsoft.Extensions.Localization.Abstractions", "Microsoft.Extensions.Logging.Abstractions", "Microsoft.Extensions.Options", "Newtonsoft.Json", } ),
            ( "OrchardCore.ResourceManagement.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.AspNetCore.Mvc.ViewFeatures", "Microsoft.AspNetCore.Razor.Runtime", } ),
            ( "OrchardCore.Scripting.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.Extensions.DependencyInjection", "Microsoft.Extensions.Localization.Abstractions", } ),
            ( "OrchardCore.Security.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.AspNetCore.Identity", } ),
            ( "OrchardCore.Setup.Abstractions", Enumerable.Empty<string>(), Enumerable.Empty<string>() ),
            ( "OrchardCore.XmlRpc.Abstractions", Enumerable.Empty<string>(), new string[] { "Microsoft.AspNetCore.Mvc.Core", "Microsoft.Extensions.DependencyInjection", } ),

            // Rank 1
            ( "OrchardCore.Admin.Abstractions", new string[] { "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Security.Abstractions", }, new string[] { "Microsoft.AspNetCore.Mvc.Abstractions", "Microsoft.AspNetCore.Mvc.Core", } ),
            ( "OrchardCore.Environment.Shell.Abstractions", new string[] { "OrchardCore.Environment.Extensions.Abstractions", }, new string[] { "Microsoft.Extensions.Configuration", "Microsoft.Extensions.DependencyInjection", "Microsoft.Extensions.Logging.Abstractions", "Newtonsoft.Json", } ),
            ( "OrchardCore.FileStorage.AzureBlob", new string[] { "OrchardCore.FileStorage.Abstractions", "OrchardCore.Modules.Abstractions", }, new string[] { "WindowsAzure.Storage", } ),
            ( "OrchardCore.FileStorage.FileSystem", new string[] { "OrchardCore.FileStorage.Abstractions", }, new string[] { "Microsoft.Extensions.FileProviders.Physical", } ),
            ( "OrchardCore.Localization.Core", new string[] { "OrchardCore.Localization.Abstractions", }, new string[] { "Microsoft.AspNetCore.Hosting.Abstractions", "Microsoft.Extensions.Caching.Abstractions", "Microsoft.Extensions.Localization", "Microsoft.Extensions.Localization.Abstractions", } ),
            ( "OrchardCore.Lucene.Core", new string[] { "OrchardCore.Lucene.Abstractions", "OrchardCore.Queries.Abstractions", }, new string[] { "Lucene.Net.QueryParser", "Microsoft.Extensions.DependencyInjection.Abstractions", "Newtonsoft.Json", } ),
            ( "OrchardCore.Module.Targets", new string[] { "OrchardCore.Modules.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Mvc.Abstractions", new string[] { "OrchardCore.Entities", "OrchardCore.Modules.Abstractions", }, new string[] { "Microsoft.AspNetCore.Mvc.Core", "Microsoft.AspNetCore.Mvc.Razor", "Microsoft.Extensions.Localization.Abstractions", } ),
            ( "OrchardCore.ResourceManagement", new string[] { "OrchardCore.ResourceManagement.Abstractions", }, new string[] { "System.Collections.Specialized", } ),
            ( "OrchardCore.Scripting.Core", new string[] { "OrchardCore.Scripting.Abstractions", }, new string[] { "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Scripting.JavaScript", new string[] { "OrchardCore.Scripting.Abstractions", }, new string[] { "Jint", "Microsoft.Extensions.Caching.Abstractions", "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Users.Abstractions", new string[] { "OrchardCore.Security.Abstractions", }, Enumerable.Empty<string>() ),

            // Rank 2
            ( "OrchardCore.BackgroundTasks", new string[] { "OrchardCore.BackgroundTasks.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", }, new string[] { "Microsoft.AspNetCore.Hosting.Abstractions", "Microsoft.Extensions.Logging.Abstractions", } ),
            ( "OrchardCore.DeferredTasks", new string[] { "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Environment.Shell.Abstractions", }, new string[] { "Microsoft.AspNetCore.Http.Abstractions", "Microsoft.Extensions.Logging.Abstractions", } ),
            ( "OrchardCore.Diagnostics.Elm", new string[] { "OrchardCore.Module.Targets", }, new string[] { "Microsoft.AspNetCore.Diagnostics.Elm", } ),
            ( "OrchardCore.Environment.Commands", new string[] { "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", }, new string[] { "Microsoft.Extensions.DependencyInjection.Abstractions", "Microsoft.Extensions.Localization.Abstractions", } ),
            ( "OrchardCore.Environment.Extensions", new string[] { "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Parser.Yaml", }, new string[] { "Microsoft.Extensions.Caching.Abstractions", "Microsoft.Extensions.Localization.Abstractions", "Microsoft.Extensions.Options", "System.Threading.Tasks.Parallel", } ),
            ( "OrchardCore.Environment.Shell", new string[] { "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Parser.Yaml", }, new string[] { "Microsoft.Extensions.Configuration.Abstractions", "Microsoft.Extensions.Configuration.Json", "Microsoft.Extensions.Configuration.Xml", "Microsoft.Extensions.DependencyInjection", "Microsoft.Extensions.Localization.Abstractions", "Microsoft.Extensions.Logging.Abstractions", "Microsoft.Extensions.Options", "System.Threading.Tasks.Parallel", } ),
            ( "OrchardCore.Feeds.Abstractions", new string[] { "OrchardCore.Mvc.Abstractions", }, new string[] { "Microsoft.AspNetCore.Mvc.Abstractions", } ),
            ( "OrchardCore.HomeRoute", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Logging.NLog", new string[] { "OrchardCore.Environment.Shell.Abstractions", }, new string[] { "NLog.Web.AspNetCore", "System.Security.AccessControl", } ),
            ( "OrchardCore.Mvc.Core", new string[] { "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Mvc.Abstractions", }, new string[] { "Microsoft.AspNetCore.Mvc", "Microsoft.AspNetCore.Routing", "Microsoft.Extensions.DependencyInjection.Abstractions", "Microsoft.Extensions.FileProviders.Abstractions", "Microsoft.Extensions.FileProviders.Physical", "Microsoft.Extensions.Logging.Abstractions", } ),
            ( "OrchardCore.Recipes.Implementations", new string[] { "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Scripting.Abstractions", }, new string[] { "Microsoft.AspNetCore.Hosting.Abstractions", "Microsoft.Extensions.DependencyInjection.Abstractions", "Microsoft.Extensions.FileSystemGlobbing", } ),
            ( "OrchardCore.ResponseCache", new string[] { "OrchardCore.Module.Targets", }, new string[] { "Microsoft.AspNetCore.ResponseCaching", } ),
            ( "OrchardCore.Security", new string[] { "OrchardCore.Mvc.Abstractions", "OrchardCore.Security.Abstractions", }, new string[] { "Microsoft.AspNetCore.Authorization", } ),
            ( "OrchardCore.Theme.Targets", new string[] { "OrchardCore.Module.Targets", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Users.Core", new string[] { "OrchardCore.Entities", "OrchardCore.Security.Abstractions", "OrchardCore.Users.Abstractions", }, new string[] { "Microsoft.AspNetCore.Identity", "Microsoft.Extensions.DependencyInjection", "Microsoft.Extensions.Localization.Abstractions", "YesSql.Core", } ),
            ( "OrchardCore.XmlRpc", new string[] { "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.XmlRpc.Abstractions", }, new string[] { "Microsoft.AspNetCore.Mvc.Formatters.Xml", "Microsoft.AspNetCore.Mvc.ViewFeatures", "Microsoft.Extensions.DependencyInjection", } ),

            // Rank 3
            ( "OrchardCore.ContentManagement.Abstractions", new string[] { "OrchardCore.Mvc.Core", }, new string[] { "Microsoft.AspNetCore.Html.Abstractions", "Microsoft.AspNetCore.Routing.Abstractions", "Newtonsoft.Json", } ),
            ( "OrchardCore.Data", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell", "OrchardCore.Modules.Abstractions", }, new string[] { "Microsoft.Extensions.DependencyInjection.Abstractions", "Microsoft.Extensions.Logging.Abstractions", "Newtonsoft.Json", "YesSql.Provider.MySql", "YesSql.Provider.PostgreSql", "YesSql.Provider.SqLite", "YesSql.Provider.SqlServer", } ),
            ( "OrchardCore.DisplayManagement", new string[] { "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Mvc.Core", }, new string[] { "Castle.Core", "Microsoft.AspNetCore.Html.Abstractions", "Microsoft.AspNetCore.Mvc.Localization", "Microsoft.Extensions.Logging.Abstractions", "System.Diagnostics.TraceSource", "System.Reflection.Extensions", } ),
            ( "OrchardCore.Environment.Navigation", new string[] { "OrchardCore.Environment.Shell", "OrchardCore.Security", }, new string[] { "Microsoft.AspNetCore.Mvc.Core", "Microsoft.AspNetCore.Mvc.ViewFeatures", "Microsoft.AspNetCore.Routing", } ),
            ( "OrchardCore.Environment.Shell.Data", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Shell", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Feeds.Core", new string[] { "OrchardCore.Feeds.Abstractions", }, new string[] { "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Hosting.Console", new string[] { "OrchardCore.Environment.Commands", }, new string[] { "Microsoft.AspNetCore.Hosting", "Microsoft.Extensions.DependencyInjection.Abstractions", } ),
            ( "OrchardCore.Modules", new string[] { "OrchardCore.Environment.Extensions", "OrchardCore.Environment.Shell", "OrchardCore.Modules.Abstractions", }, new string[] { "Microsoft.AspNetCore.Hosting.Abstractions", "Microsoft.AspNetCore.Http", "Microsoft.AspNetCore.StaticFiles", "Microsoft.Extensions.DependencyInjection.Abstractions", "Microsoft.Extensions.FileProviders.Composite", "Microsoft.Extensions.Localization", "Microsoft.Extensions.Logging", } ),
            ( "OrchardCore.Mvc.HelloWorld", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Mvc.Core", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Scripting", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Mvc.Core", "OrchardCore.Scripting.Core", "OrchardCore.Scripting.JavaScript", }, new string[] { "Microsoft.Extensions.DependencyInjection", } ),

            // Rank 4
            ( "OrchardCore.ContentManagement", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", }, new string[] { "Microsoft.AspNetCore.Html.Abstractions", "Microsoft.AspNetCore.Mvc.DataAnnotations", "Microsoft.AspNetCore.Mvc.ViewFeatures", "Microsoft.Extensions.Caching.Abstractions", } ),
            ( "OrchardCore.ContentManagement.Display", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.DisplayManagement", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Deployment.Abstractions", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Recipes.Abstractions", }, new string[] { "Microsoft.Extensions.DependencyInjection.Abstractions", } ),
            ( "OrchardCore.Diagnostics", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, new string[] { "Microsoft.AspNetCore.Diagnostics", "Microsoft.AspNetCore.Mvc.ViewFeatures", "Microsoft.AspNetCore.StaticFiles", "Microsoft.Extensions.DependencyInjection.Abstractions", } ),
            ( "OrchardCore.DisplayManagement.Liquid", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Liquid.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Entities.DisplayManagement", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Entities", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Environment.Cache", new string[] { "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Modules", }, new string[] { "Microsoft.AspNetCore.Http.Abstractions", "Microsoft.Extensions.Caching.Abstractions", "Microsoft.Extensions.Caching.Memory", } ),
            ( "OrchardCore.Feeds", new string[] { "OrchardCore.Feeds.Core", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, new string[] { "Microsoft.AspNetCore.Mvc.Abstractions", "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Indexing.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Media.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.FileStorage.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Menu.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.MetaWeblog.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.XmlRpc.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Mvc", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Modules", "OrchardCore.Mvc.Core", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Nancy.Core", new string[] { "OrchardCore.Modules", }, new string[] { "Microsoft.AspNetCore.Owin", "Microsoft.Extensions.DependencyInjection.Abstractions", "Nancy", } ),
            ( "OrchardCore.Navigation", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Security", }, new string[] { "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Roles", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Security.Abstractions", }, new string[] { "Microsoft.AspNetCore.Identity", "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Settings", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities", "OrchardCore.Environment.Navigation", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Setup.Abstractions", }, new string[] { "Microsoft.AspNetCore.Mvc", "Microsoft.Extensions.Caching.Abstractions", "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Setup", new string[] { "OrchardCore.Data", "OrchardCore.DisplayManagement", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Setup.Abstractions", }, new string[] { "Microsoft.AspNetCore.Identity", } ),
            ( "OrchardCore.Tenants", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, new string[] { "Microsoft.AspNetCore.StaticFiles", "Microsoft.Extensions.DependencyInjection", } ),
            ( "SafeMode", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Theme.Targets", }, new string[] { "Microsoft.AspNetCore.Mvc", "Microsoft.AspNetCore.Mvc.TagHelpers", } ),
            ( "TheAdmin", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Theme.Targets", }, new string[] { "Microsoft.AspNetCore.Mvc", "Microsoft.AspNetCore.Mvc.TagHelpers", } ),
            ( "TheAgencyTheme", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Theme.Targets", }, new string[] { "Microsoft.AspNetCore.Mvc", "Microsoft.AspNetCore.Mvc.TagHelpers", } ),

            // Rank 5
            ( "OrchardCore.Admin", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Settings", }, new string[] { "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Application.Mvc.Targets", new string[] { "OrchardCore.Application.Targets", "OrchardCore.Mvc", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Commons", new string[] { "OrchardCore.BackgroundTasks", "OrchardCore.Data", "OrchardCore.DeferredTasks", "OrchardCore.DisplayManagement", "OrchardCore.DisplayManagement.Liquid", "OrchardCore.Environment.Cache", "OrchardCore.Environment.Extensions", "OrchardCore.Environment.Shell.Data", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement", }, new string[] { "Microsoft.Extensions.DependencyInjection.Abstractions", } ),
            ( "OrchardCore.ContentPreview", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Module.Targets", "OrchardCore.Security", "OrchardCore.Settings", }, new string[] { "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.ContentTypes.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", }, new string[] { "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.Deployment.Core", new string[] { "OrchardCore.Deployment.Abstractions", }, new string[] { "Microsoft.Extensions.DependencyInjection.Abstractions", } ),
            ( "OrchardCore.DynamicCache", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Core", }, new string[] { "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.Features", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Deployment.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.ResourceManagement.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Layers", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Scripting.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Media.Services", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Media.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Menu", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, new string[] { "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Nancy", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Nancy.Core", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Nancy.HelloWorld", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Nancy.Core", }, new string[] { "Nancy", } ),
            ( "OrchardCore.Resources", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement.Abstractions", }, new string[] { "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.Themes", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Settings", }, new string[] { "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.Title", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Security.Abstractions", }, new string[] { "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Users", new string[] { "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Commands", "OrchardCore.Environment.Navigation", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Setup.Abstractions", "OrchardCore.Users.Core", }, new string[] { "Microsoft.AspNetCore.Identity", "Microsoft.Extensions.DependencyInjection", } ),
            ( "TheBlogTheme", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.ResourceManagement", "OrchardCore.Theme.Targets", }, new string[] { "Microsoft.AspNetCore.Mvc", "Microsoft.Extensions.Configuration.Json", } ),
            ( "TheTheme", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.ResourceManagement", "OrchardCore.Theme.Targets", }, new string[] { "Microsoft.AspNetCore.Mvc", "Microsoft.Extensions.Configuration.Json", } ),

            // Rank 6
            ( "OrchardCore.Alias", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", }, new string[] { "Microsoft.Extensions.DependencyInjection.Abstractions", } ),
            ( "OrchardCore.Application.Nancy.Targets", new string[] { "OrchardCore.Application.Targets", "OrchardCore.Nancy", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Autoroute", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Security", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Body", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.ContentFields", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", }, new string[] { "Microsoft.AspNetCore.Mvc", "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.Contents", new string[] { "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Feeds.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Navigation", "OrchardCore.Recipes.Abstractions", "OrchardCore.Scripting.Abstractions", "OrchardCore.Settings", }, new string[] { "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.ContentTypes", new string[] { "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Deployment.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement", }, new string[] { "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.CustomSettings", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Deployment", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement", "OrchardCore.Data.Abstractions", "OrchardCore.Deployment.Core", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, new string[] { "Microsoft.Extensions.DependencyInjection", "System.IO.Compression.ZipFile", } ),
            ( "OrchardCore.Deployment.Remote", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Deployment.Core", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", }, new string[] { "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Flows", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.ResourceManagement.Abstractions", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Indexing", new string[] { "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Module.Targets", }, new string[] { "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Liquid", new string[] { "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data", "OrchardCore.DisplayManagement", "OrchardCore.DisplayManagement.Liquid", "OrchardCore.Indexing.Abstractions", "OrchardCore.Module.Targets", }, new string[] { "Fluid.Core", "Microsoft.Extensions.DependencyInjection.Abstractions", } ),
            ( "OrchardCore.Localization", new string[] { "OrchardCore.Environment.Shell", "OrchardCore.Features", "OrchardCore.Localization.Abstractions", "OrchardCore.Localization.Core", }, new string[] { "Microsoft.AspNetCore.Mvc.Localization", } ),
            ( "OrchardCore.Lucene", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.BackgroundTasks.Abstractions", "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Lucene.Core", "OrchardCore.Module.Targets", "OrchardCore.Security", }, new string[] { "Lucene.Net.Analysis.Common", "Lucene.Net.QueryParser", "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Markdown", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", }, new string[] { "Markdig", "Microsoft.Extensions.DependencyInjection", } ),
            ( "OrchardCore.Media", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell", "OrchardCore.FileStorage.FileSystem", "OrchardCore.Liquid.Abstractions", "OrchardCore.Media.Abstractions", "OrchardCore.Media.Services", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Security", "OrchardCore.Security.Abstractions", "OrchardCore.XmlRpc.Abstractions", }, new string[] { "Microsoft.AspNetCore.Mvc.TagHelpers", "Microsoft.AspNetCore.Mvc.ViewFeatures", "Microsoft.AspNetCore.StaticFiles", "Microsoft.Extensions.DependencyInjection", "MimeMapping", "OrchardCore.ImageSharp.Web", } ),
            ( "OrchardCore.Mvc.Web", new string[] { "OrchardCore.Application.Mvc.Targets", "OrchardCore.Diagnostics.Elm", "OrchardCore.Hosting.Console", "OrchardCore.Mvc.HelloWorld", }, new string[] { "Microsoft.AspNetCore", "Microsoft.AspNetCore.Diagnostics", "Microsoft.AspNetCore.Mvc.ViewFeatures", "Microsoft.AspNetCore.Server.IISIntegration", "Microsoft.AspNetCore.Server.Kestrel", "Microsoft.AspNetCore.StaticFiles", "Microsoft.Extensions.Localization.Abstractions", "Microsoft.Extensions.Logging.Console", "System.Collections.Specialized", "System.Dynamic.Runtime", "System.Linq", } ),
            ( "OrchardCore.OpenId", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Roles", "OrchardCore.Settings", "OrchardCore.Users", }, new string[] { "AspNet.Security.OAuth.Validation", "Microsoft.AspNetCore.Authentication.JwtBearer", "OpenIddict", } ),
            ( "OrchardCore.Recipes", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Commands", "OrchardCore.Features", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Implementations", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Templates", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.DisplayManagement.Liquid", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", }, new string[] { "Microsoft.Extensions.DependencyInjection.Abstractions", "Microsoft.Extensions.Localization", } ),
            ( "OrchardCore.Widgets", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, Enumerable.Empty<string>() ),

            // Rank 7
            ( "OrchardCore.Demo", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.BackgroundTasks.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Contents", "OrchardCore.Data.Abstractions", "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Commands", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement", "OrchardCore.ResourceManagement.Abstractions", "OrchardCore.Users.Core", }, new string[] { "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.Lists", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Contents", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Media.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.ResourceManagement.Abstractions", "OrchardCore.Users.Abstractions", }, new string[] { "Microsoft.Extensions.Configuration.Json", } ),
            ( "OrchardCore.Media.Azure", new string[] { "OrchardCore.Admin", "OrchardCore.FileStorage.AzureBlob", "OrchardCore.Media", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Nancy.Web", new string[] { "OrchardCore.Application.Nancy.Targets", "OrchardCore.Nancy.HelloWorld", }, new string[] { "Microsoft.AspNetCore", "Microsoft.AspNetCore.Diagnostics", "Microsoft.AspNetCore.Server.IISIntegration", "Microsoft.AspNetCore.Server.Kestrel", "Microsoft.Extensions.DependencyInjection.Abstractions", "Microsoft.Extensions.Logging.Console", "System.Collections.Specialized", "System.Dynamic.Runtime", "System.Linq", } ),
            ( "OrchardCore.Queries", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Liquid.Abstractions", "OrchardCore.Lucene", "OrchardCore.Module.Targets", "OrchardCore.Queries.Abstractions", }, new string[] { "Irony.Core", "Microsoft.Extensions.DependencyInjection", } ),

            // Rank 8
            ( "OrchardCore.Application.Cms.Targets", new string[] { "OrchardCore.Admin", "OrchardCore.Alias", "OrchardCore.Application.Targets", "OrchardCore.Autoroute", "OrchardCore.Body", "OrchardCore.Commons", "OrchardCore.ContentFields", "OrchardCore.ContentPreview", "OrchardCore.Contents", "OrchardCore.ContentTypes", "OrchardCore.CustomSettings", "OrchardCore.Deployment", "OrchardCore.Deployment.Remote", "OrchardCore.Diagnostics", "OrchardCore.DynamicCache", "OrchardCore.Features", "OrchardCore.Feeds", "OrchardCore.Flows", "OrchardCore.HomeRoute", "OrchardCore.Indexing", "OrchardCore.Layers", "OrchardCore.Liquid", "OrchardCore.Lists", "OrchardCore.Localization", "OrchardCore.Lucene", "OrchardCore.Markdown", "OrchardCore.Media", "OrchardCore.Media.Azure", "OrchardCore.Menu", "OrchardCore.Mvc", "OrchardCore.Navigation", "OrchardCore.Queries", "OrchardCore.Recipes", "OrchardCore.Resources", "OrchardCore.ResponseCache", "OrchardCore.Roles", "OrchardCore.Scripting", "OrchardCore.Settings", "OrchardCore.Setup", "OrchardCore.Templates", "OrchardCore.Tenants", "OrchardCore.Themes", "OrchardCore.Title", "OrchardCore.Users", "OrchardCore.Widgets", "OrchardCore.XmlRpc", "SafeMode", "TheAdmin", "TheAgencyTheme", "TheBlogTheme", "TheTheme", }, Enumerable.Empty<string>() ),
            ( "OrchardCore.Tests", new string[] { "OrchardCore.ContentManagement", "OrchardCore.Data", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Extensions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell", "OrchardCore.Hosting.Console", "OrchardCore.Liquid", "OrchardCore.Localization.Abstractions", "OrchardCore.Localization.Core", "OrchardCore.Parser.Yaml", "OrchardCore.Queries", "OrchardCore.Recipes.Implementations", }, new string[] { "Microsoft.Extensions.DependencyInjection", "Microsoft.NET.Test.Sdk", "Moq", "xunit", "xunit.analyzers", "xunit.runner.visualstudio", } ),

            // Rank 9
            ( "OrchardCore.Cms.Web", new string[] { "OrchardCore.Application.Cms.Targets", "OrchardCore.Hosting.Console", "OrchardCore.Logging.NLog", }, new string[] { "Microsoft.AspNetCore", "Microsoft.AspNetCore.Mvc.Razor.ViewCompilation", } ),
        };

        public string MainProject => "OrchardCore.Cms.Web";
    }
}
