using System.Collections.Generic;
using System.Linq;

namespace SolutionGenerator.Solutions
{
    // https://github.com/OrchardCMS/OrchardCore
    // Total Projects: 127
    // Total ProjectRefs: 529
    // Total PackageRefs: 237
    // Unique PackageRefs: 84

    class OrchardCoreSolution : ISolution
    {
        public IList<(string Name, IEnumerable<string> ProjectReferences, IEnumerable<(string Name, string Version)> PackageReferences)> Projects { get; } =
            new List<(string Name, IEnumerable<string> ProjectReferences, IEnumerable<(string Name, string Version)> PackageReferences)>
        {
            // Rank 0
            ( "OrchardCore.Application.Targets", Enumerable.Empty<string>(), Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.BackgroundTasks.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("System.ComponentModel" ,"4.3.0"), } ),
            ( "OrchardCore.Data.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("YesSql.Core" ,"2.0.0-beta-1097"), } ),
            ( "OrchardCore.DeferredTasks.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("System.ComponentModel" ,"4.3.0"), } ),
            ( "OrchardCore.Entities", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Newtonsoft.Json" ,"10.0.3"), } ),
            ( "OrchardCore.Environment.Cache.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.Primitives" ,"2.0.0"), } ),
            ( "OrchardCore.Environment.Extensions.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.FileProviders.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Logging.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.FileStorage.Abstractions", Enumerable.Empty<string>(), Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Liquid.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Fluid.Core" ,"1.0.0-beta-9399"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), ("Microsoft.Extensions.Options" ,"2.0.0"), } ),
            ( "OrchardCore.Localization.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Localization" ,"2.0.1"), ("Microsoft.Extensions.Caching.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), } ),
            ( "OrchardCore.Lucene.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Lucene.Net" ,"4.8.0-beta00004"), } ),
            ( "OrchardCore.Modules.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Routing" ,"2.0.1"), ("Microsoft.Extensions.Configuration.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), } ),
            ( "OrchardCore.Parser.Yaml", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration" ,"2.0.0"), ("Microsoft.Extensions.Configuration.FileExtensions" ,"2.0.0"), ("YamlDotNet" ,"4.2.1"), } ),
            ( "OrchardCore.Queries.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Newtonsoft.Json" ,"10.0.3"), } ),
            ( "OrchardCore.Recipes.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.FileProviders.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.Logging.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Options" ,"2.0.0"), ("Newtonsoft.Json" ,"10.0.3"), } ),
            ( "OrchardCore.ResourceManagement.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"2.0.1"), ("Microsoft.AspNetCore.Razor.Runtime" ,"2.0.1"), } ),
            ( "OrchardCore.Scripting.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), } ),
            ( "OrchardCore.Security.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"2.0.1"), } ),
            ( "OrchardCore.Setup.Abstractions", Enumerable.Empty<string>(), Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.XmlRpc.Abstractions", Enumerable.Empty<string>(), new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Core" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),

            // Rank 1
            ( "OrchardCore.Admin.Abstractions", new string[] { "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Security.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Abstractions" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.Core" ,"2.0.1"), } ),
            ( "OrchardCore.Environment.Shell.Abstractions", new string[] { "OrchardCore.Environment.Extensions.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration" ,"2.0.0"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), ("Microsoft.Extensions.Logging.Abstractions" ,"2.0.0"), ("Newtonsoft.Json" ,"10.0.3"), } ),
            ( "OrchardCore.FileStorage.AzureBlob", new string[] { "OrchardCore.FileStorage.Abstractions", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("WindowsAzure.Storage" ,"8.5.0"), } ),
            ( "OrchardCore.FileStorage.FileSystem", new string[] { "OrchardCore.FileStorage.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.FileProviders.Physical" ,"2.0.0"), } ),
            ( "OrchardCore.Localization.Core", new string[] { "OrchardCore.Localization.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.Caching.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Localization" ,"2.0.1"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), } ),
            ( "OrchardCore.Lucene.Core", new string[] { "OrchardCore.Lucene.Abstractions", "OrchardCore.Queries.Abstractions", }, new (string Name, string Version)[] { ("Lucene.Net.QueryParser" ,"4.8.0-beta00004"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Newtonsoft.Json" ,"10.0.3"), } ),
            ( "OrchardCore.Module.Targets", new string[] { "OrchardCore.Modules.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Mvc.Abstractions", new string[] { "OrchardCore.Entities", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Core" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.Razor" ,"2.0.1"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), } ),
            ( "OrchardCore.ResourceManagement", new string[] { "OrchardCore.ResourceManagement.Abstractions", }, new (string Name, string Version)[] { ("System.Collections.Specialized" ,"4.3.0"), } ),
            ( "OrchardCore.Scripting.Core", new string[] { "OrchardCore.Scripting.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Scripting.JavaScript", new string[] { "OrchardCore.Scripting.Abstractions", }, new (string Name, string Version)[] { ("Jint" ,"2.11.10"), ("Microsoft.Extensions.Caching.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Users.Abstractions", new string[] { "OrchardCore.Security.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),

            // Rank 2
            ( "OrchardCore.BackgroundTasks", new string[] { "OrchardCore.BackgroundTasks.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.Logging.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.DeferredTasks", new string[] { "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Environment.Shell.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Http.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.Logging.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.Diagnostics.Elm", new string[] { "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Diagnostics.Elm" ,"0.2.2"), } ),
            ( "OrchardCore.Environment.Commands", new string[] { "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), } ),
            ( "OrchardCore.Environment.Extensions", new string[] { "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Parser.Yaml", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Caching.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.Options" ,"2.0.0"), ("System.Threading.Tasks.Parallel" ,"4.3.0"), } ),
            ( "OrchardCore.Environment.Shell", new string[] { "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Parser.Yaml", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), ("Microsoft.Extensions.Configuration.Xml" ,"2.0.0"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.Logging.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Options" ,"2.0.0"), ("System.Threading.Tasks.Parallel" ,"4.3.0"), } ),
            ( "OrchardCore.Feeds.Abstractions", new string[] { "OrchardCore.Mvc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Abstractions" ,"2.0.1"), } ),
            ( "OrchardCore.HomeRoute", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Logging.NLog", new string[] { "OrchardCore.Environment.Shell.Abstractions", }, new (string Name, string Version)[] { ("NLog.Web.AspNetCore" ,"4.4.1"), ("System.Security.AccessControl" ,"4.4.0"), } ),
            ( "OrchardCore.Mvc.Core", new string[] { "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Mvc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"2.0.1"), ("Microsoft.AspNetCore.Routing" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.FileProviders.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.FileProviders.Physical" ,"2.0.0"), ("Microsoft.Extensions.Logging.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.Recipes.Implementations", new string[] { "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Scripting.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.FileSystemGlobbing" ,"2.0.0"), } ),
            ( "OrchardCore.ResponseCache", new string[] { "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.ResponseCaching" ,"2.0.1"), } ),
            ( "OrchardCore.Security", new string[] { "OrchardCore.Mvc.Abstractions", "OrchardCore.Security.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Authorization" ,"2.0.1"), } ),
            ( "OrchardCore.Theme.Targets", new string[] { "OrchardCore.Module.Targets", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Users.Core", new string[] { "OrchardCore.Entities", "OrchardCore.Security.Abstractions", "OrchardCore.Users.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), ("YesSql.Core" ,"2.0.0-beta-1097"), } ),
            ( "OrchardCore.XmlRpc", new string[] { "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.XmlRpc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Formatters.Xml" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),

            // Rank 3
            ( "OrchardCore.ContentManagement.Abstractions", new string[] { "OrchardCore.Mvc.Core", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Html.Abstractions" ,"2.0.0"), ("Microsoft.AspNetCore.Routing.Abstractions" ,"2.0.1"), ("Newtonsoft.Json" ,"10.0.3"), } ),
            ( "OrchardCore.Data", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Logging.Abstractions" ,"2.0.0"), ("Newtonsoft.Json" ,"10.0.3"), ("YesSql.Provider.MySql" ,"1.0.0-beta-1097"), ("YesSql.Provider.PostgreSql" ,"1.0.0-beta-1097"), ("YesSql.Provider.SqLite" ,"1.0.0-beta-1097"), ("YesSql.Provider.SqlServer" ,"1.0.0-beta-1097"), } ),
            ( "OrchardCore.DisplayManagement", new string[] { "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Mvc.Core", }, new (string Name, string Version)[] { ("Castle.Core" ,"4.1.1"), ("Microsoft.AspNetCore.Html.Abstractions" ,"2.0.0"), ("Microsoft.AspNetCore.Mvc.Localization" ,"2.0.1"), ("Microsoft.Extensions.Logging.Abstractions" ,"2.0.0"), ("System.Diagnostics.TraceSource" ,"4.3.0"), ("System.Reflection.Extensions" ,"4.3.0"), } ),
            ( "OrchardCore.Environment.Navigation", new string[] { "OrchardCore.Environment.Shell", "OrchardCore.Security", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Core" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"2.0.1"), ("Microsoft.AspNetCore.Routing" ,"2.0.1"), } ),
            ( "OrchardCore.Environment.Shell.Data", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Shell", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Feeds.Core", new string[] { "OrchardCore.Feeds.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Hosting.Console", new string[] { "OrchardCore.Environment.Commands", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.Modules", new string[] { "OrchardCore.Environment.Extensions", "OrchardCore.Environment.Shell", "OrchardCore.Modules.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Hosting.Abstractions" ,"2.0.1"), ("Microsoft.AspNetCore.Http" ,"2.0.1"), ("Microsoft.AspNetCore.StaticFiles" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.FileProviders.Composite" ,"2.0.0"), ("Microsoft.Extensions.Localization" ,"2.0.1"), ("Microsoft.Extensions.Logging" ,"2.0.0"), } ),
            ( "OrchardCore.Mvc.HelloWorld", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Mvc.Core", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Scripting", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Mvc.Core", "OrchardCore.Scripting.Core", "OrchardCore.Scripting.JavaScript", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),

            // Rank 4
            ( "OrchardCore.ContentManagement", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Html.Abstractions" ,"2.0.0"), ("Microsoft.AspNetCore.Mvc.DataAnnotations" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"2.0.1"), ("Microsoft.Extensions.Caching.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.ContentManagement.Display", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.DisplayManagement", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Deployment.Abstractions", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Recipes.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.Diagnostics", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Diagnostics" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"2.0.1"), ("Microsoft.AspNetCore.StaticFiles" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.DisplayManagement.Liquid", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Liquid.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Entities.DisplayManagement", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Entities", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Environment.Cache", new string[] { "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Modules", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Http.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.Caching.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Caching.Memory" ,"2.0.0"), } ),
            ( "OrchardCore.Feeds", new string[] { "OrchardCore.Feeds.Core", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Indexing.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Media.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.FileStorage.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Menu.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.MetaWeblog.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.XmlRpc.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Mvc", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Modules", "OrchardCore.Mvc.Core", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Nancy.Core", new string[] { "OrchardCore.Modules", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Owin" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Nancy" ,"2.0.0-clinteastwood"), } ),
            ( "OrchardCore.Navigation", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Security", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Roles", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Security.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Settings", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities", "OrchardCore.Environment.Navigation", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Setup.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"2.0.1"), ("Microsoft.Extensions.Caching.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Setup", new string[] { "OrchardCore.Data", "OrchardCore.DisplayManagement", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Setup.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"2.0.1"), } ),
            ( "OrchardCore.Tenants", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.StaticFiles" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "SafeMode", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.TagHelpers" ,"2.0.1"), } ),
            ( "TheAdmin", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.TagHelpers" ,"2.0.1"), } ),
            ( "TheAgencyTheme", new string[] { "OrchardCore.DisplayManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.TagHelpers" ,"2.0.1"), } ),

            // Rank 5
            ( "OrchardCore.Admin", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Settings", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Application.Mvc.Targets", new string[] { "OrchardCore.Application.Targets", "OrchardCore.Mvc", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Commons", new string[] { "OrchardCore.BackgroundTasks", "OrchardCore.Data", "OrchardCore.DeferredTasks", "OrchardCore.DisplayManagement", "OrchardCore.DisplayManagement.Liquid", "OrchardCore.Environment.Cache", "OrchardCore.Environment.Extensions", "OrchardCore.Environment.Shell.Data", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.ContentPreview", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Module.Targets", "OrchardCore.Security", "OrchardCore.Settings", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.ContentTypes.Abstractions", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.Deployment.Core", new string[] { "OrchardCore.Deployment.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.DynamicCache", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Cache.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Core", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.Features", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Deployment.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.ResourceManagement.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Layers", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Scripting.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Media.Services", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Media.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Menu", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Nancy", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Nancy.Core", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Nancy.HelloWorld", new string[] { "OrchardCore.Module.Targets", "OrchardCore.Nancy.Core", }, new (string Name, string Version)[] { ("Nancy" ,"2.0.0-clinteastwood"), } ),
            ( "OrchardCore.Resources", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.Themes", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Settings", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.Title", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Security.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Users", new string[] { "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Commands", "OrchardCore.Environment.Navigation", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Setup.Abstractions", "OrchardCore.Users.Core", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Identity" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "TheBlogTheme", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.ResourceManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"2.0.1"), ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "TheTheme", new string[] { "OrchardCore.ContentManagement", "OrchardCore.DisplayManagement", "OrchardCore.ResourceManagement", "OrchardCore.Theme.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"2.0.1"), ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),

            // Rank 6
            ( "OrchardCore.Alias", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.Application.Nancy.Targets", new string[] { "OrchardCore.Application.Targets", "OrchardCore.Nancy", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Autoroute", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Security", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Body", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.ContentFields", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc" ,"2.0.1"), ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.Contents", new string[] { "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Feeds.Abstractions", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Navigation", "OrchardCore.Recipes.Abstractions", "OrchardCore.Scripting.Abstractions", "OrchardCore.Settings", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.ContentTypes", new string[] { "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Deployment.Abstractions", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.CustomSettings", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Deployment", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement", "OrchardCore.Data.Abstractions", "OrchardCore.Deployment.Core", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), ("System.IO.Compression.ZipFile" ,"4.3.0"), } ),
            ( "OrchardCore.Deployment.Remote", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Deployment.Core", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Flows", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.ResourceManagement.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Indexing", new string[] { "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Liquid", new string[] { "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data", "OrchardCore.DisplayManagement", "OrchardCore.DisplayManagement.Liquid", "OrchardCore.Indexing.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Fluid.Core" ,"1.0.0-beta-9399"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), } ),
            ( "OrchardCore.Localization", new string[] { "OrchardCore.Environment.Shell", "OrchardCore.Features", "OrchardCore.Localization.Abstractions", "OrchardCore.Localization.Core", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.Localization" ,"2.0.1"), } ),
            ( "OrchardCore.Lucene", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.BackgroundTasks.Abstractions", "OrchardCore.ContentManagement", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.Lucene.Core", "OrchardCore.Module.Targets", "OrchardCore.Security", }, new (string Name, string Version)[] { ("Lucene.Net.Analysis.Common" ,"4.8.0-beta00004"), ("Lucene.Net.QueryParser" ,"4.8.0-beta00004"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Markdown", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Indexing.Abstractions", "OrchardCore.Liquid.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", }, new (string Name, string Version)[] { ("Markdig" ,"0.13.1"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),
            ( "OrchardCore.Media", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Environment.Shell", "OrchardCore.FileStorage.FileSystem", "OrchardCore.Liquid.Abstractions", "OrchardCore.Media.Abstractions", "OrchardCore.Media.Services", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Modules.Abstractions", "OrchardCore.Recipes.Abstractions", "OrchardCore.Security", "OrchardCore.Security.Abstractions", "OrchardCore.XmlRpc.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore.Mvc.TagHelpers" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"2.0.1"), ("Microsoft.AspNetCore.StaticFiles" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), ("MimeMapping" ,"1.0.1.10"), ("OrchardCore.ImageSharp.Web" ,"1.0.0-ci0027"), } ),
            ( "OrchardCore.Mvc.Web", new string[] { "OrchardCore.Application.Mvc.Targets", "OrchardCore.Diagnostics.Elm", "OrchardCore.Hosting.Console", "OrchardCore.Mvc.HelloWorld", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore" ,"2.0.1"), ("Microsoft.AspNetCore.Diagnostics" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.ViewFeatures" ,"2.0.1"), ("Microsoft.AspNetCore.Server.IISIntegration" ,"2.0.1"), ("Microsoft.AspNetCore.Server.Kestrel" ,"2.0.1"), ("Microsoft.AspNetCore.StaticFiles" ,"2.0.1"), ("Microsoft.Extensions.Localization.Abstractions" ,"2.0.1"), ("Microsoft.Extensions.Logging.Console" ,"2.0.0"), ("System.Collections.Specialized" ,"4.3.0"), ("System.Dynamic.Runtime" ,"4.3.0"), ("System.Linq" ,"4.3.0"), } ),
            ( "OrchardCore.OpenId", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", "OrchardCore.Roles", "OrchardCore.Settings", "OrchardCore.Users", }, new (string Name, string Version)[] { ("AspNet.Security.OAuth.Validation" ,"2.0.0-rc1-0286"), ("Microsoft.AspNetCore.Authentication.JwtBearer" ,"2.0.1"), ("OpenIddict" ,"2.0.0-preview1-0657"), } ),
            ( "OrchardCore.Recipes", new string[] { "OrchardCore.Data.Abstractions", "OrchardCore.Environment.Commands", "OrchardCore.Features", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.Recipes.Implementations", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Templates", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.DisplayManagement.Liquid", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.Recipes.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Localization" ,"2.0.1"), } ),
            ( "OrchardCore.Widgets", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Data.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", }, Enumerable.Empty<(string Name, string Version)>() ),

            // Rank 7
            ( "OrchardCore.Demo", new string[] { "OrchardCore.Admin.Abstractions", "OrchardCore.BackgroundTasks.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Contents", "OrchardCore.Data.Abstractions", "OrchardCore.DeferredTasks.Abstractions", "OrchardCore.Entities.DisplayManagement", "OrchardCore.Environment.Commands", "OrchardCore.Environment.Navigation", "OrchardCore.Module.Targets", "OrchardCore.ResourceManagement", "OrchardCore.ResourceManagement.Abstractions", "OrchardCore.Users.Core", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.Lists", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Contents", "OrchardCore.ContentTypes.Abstractions", "OrchardCore.Media.Abstractions", "OrchardCore.MetaWeblog.Abstractions", "OrchardCore.Module.Targets", "OrchardCore.Mvc.Abstractions", "OrchardCore.ResourceManagement.Abstractions", "OrchardCore.Users.Abstractions", }, new (string Name, string Version)[] { ("Microsoft.Extensions.Configuration.Json" ,"2.0.0"), } ),
            ( "OrchardCore.Media.Azure", new string[] { "OrchardCore.Admin", "OrchardCore.FileStorage.AzureBlob", "OrchardCore.Media", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Nancy.Web", new string[] { "OrchardCore.Application.Nancy.Targets", "OrchardCore.Nancy.HelloWorld", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore" ,"2.0.1"), ("Microsoft.AspNetCore.Diagnostics" ,"2.0.1"), ("Microsoft.AspNetCore.Server.IISIntegration" ,"2.0.1"), ("Microsoft.AspNetCore.Server.Kestrel" ,"2.0.1"), ("Microsoft.Extensions.DependencyInjection.Abstractions" ,"2.0.0"), ("Microsoft.Extensions.Logging.Console" ,"2.0.0"), ("System.Collections.Specialized" ,"4.3.0"), ("System.Dynamic.Runtime" ,"4.3.0"), ("System.Linq" ,"4.3.0"), } ),
            ( "OrchardCore.Queries", new string[] { "OrchardCore.ContentManagement.Abstractions", "OrchardCore.ContentManagement.Display", "OrchardCore.Data.Abstractions", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Navigation", "OrchardCore.Liquid.Abstractions", "OrchardCore.Lucene", "OrchardCore.Module.Targets", "OrchardCore.Queries.Abstractions", }, new (string Name, string Version)[] { ("Irony.Core" ,"1.0.7"), ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), } ),

            // Rank 8
            ( "OrchardCore.Application.Cms.Targets", new string[] { "OrchardCore.Admin", "OrchardCore.Alias", "OrchardCore.Application.Targets", "OrchardCore.Autoroute", "OrchardCore.Body", "OrchardCore.Commons", "OrchardCore.ContentFields", "OrchardCore.ContentPreview", "OrchardCore.Contents", "OrchardCore.ContentTypes", "OrchardCore.CustomSettings", "OrchardCore.Deployment", "OrchardCore.Deployment.Remote", "OrchardCore.Diagnostics", "OrchardCore.DynamicCache", "OrchardCore.Features", "OrchardCore.Feeds", "OrchardCore.Flows", "OrchardCore.HomeRoute", "OrchardCore.Indexing", "OrchardCore.Layers", "OrchardCore.Liquid", "OrchardCore.Lists", "OrchardCore.Localization", "OrchardCore.Lucene", "OrchardCore.Markdown", "OrchardCore.Media", "OrchardCore.Media.Azure", "OrchardCore.Menu", "OrchardCore.Mvc", "OrchardCore.Navigation", "OrchardCore.Queries", "OrchardCore.Recipes", "OrchardCore.Resources", "OrchardCore.ResponseCache", "OrchardCore.Roles", "OrchardCore.Scripting", "OrchardCore.Settings", "OrchardCore.Setup", "OrchardCore.Templates", "OrchardCore.Tenants", "OrchardCore.Themes", "OrchardCore.Title", "OrchardCore.Users", "OrchardCore.Widgets", "OrchardCore.XmlRpc", "SafeMode", "TheAdmin", "TheAgencyTheme", "TheBlogTheme", "TheTheme", }, Enumerable.Empty<(string Name, string Version)>() ),
            ( "OrchardCore.Tests", new string[] { "OrchardCore.ContentManagement", "OrchardCore.Data", "OrchardCore.DisplayManagement", "OrchardCore.Environment.Extensions", "OrchardCore.Environment.Extensions.Abstractions", "OrchardCore.Environment.Shell", "OrchardCore.Hosting.Console", "OrchardCore.Liquid", "OrchardCore.Localization.Abstractions", "OrchardCore.Localization.Core", "OrchardCore.Parser.Yaml", "OrchardCore.Queries", "OrchardCore.Recipes.Implementations", }, new (string Name, string Version)[] { ("Microsoft.Extensions.DependencyInjection" ,"2.0.0"), ("Microsoft.NET.Test.Sdk" ,"15.3.0"), ("Moq" ,"4.7.99"), ("xunit" ,"2.3.0-beta2-build3683"), ("xunit.analyzers" ,"0.3.0"), ("xunit.runner.visualstudio" ,"2.3.0-beta2-build1317"), } ),

            // Rank 9
            ( "OrchardCore.Cms.Web", new string[] { "OrchardCore.Application.Cms.Targets", "OrchardCore.Hosting.Console", "OrchardCore.Logging.NLog", }, new (string Name, string Version)[] { ("Microsoft.AspNetCore" ,"2.0.1"), ("Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" ,"2.0.1"), } ),
        };

        public string MainProject => "OrchardCore.Cms.Web";
    }
}
