Install-Package System.ComponentModel -Version 4.3.0 -ProjectName ClassLib002
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib003
Install-Package YesSql.Core -Version 2.0.0-beta-1097 -ProjectName ClassLib003
Install-Package System.ComponentModel -Version 4.3.0 -ProjectName ClassLib004
Install-Package Newtonsoft.Json -Version 10.0.3 -ProjectName ClassLib005
Install-Package Microsoft.Extensions.Primitives -Version 2.0.0 -ProjectName ClassLib006
Install-Package Microsoft.AspNetCore.Hosting.Abstractions -Version 2.0.1 -ProjectName ClassLib007
Install-Package Microsoft.Extensions.FileProviders.Abstractions -Version 2.0.0 -ProjectName ClassLib007
Install-Package Microsoft.Extensions.Logging.Abstractions -Version 2.0.0 -ProjectName ClassLib007
Install-Package Fluid.Core -Version 1.0.0-beta-9399 -ProjectName ClassLib009
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib009
Install-Package Microsoft.Extensions.Options -Version 2.0.0 -ProjectName ClassLib009
Install-Package Microsoft.AspNetCore.Mvc.Localization -Version 2.0.1 -ProjectName ClassLib010
Install-Package Microsoft.Extensions.Caching.Abstractions -Version 2.0.0 -ProjectName ClassLib010
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib010
Install-Package Lucene.Net -Version 4.8.0-beta00004 -ProjectName ClassLib011
Install-Package Microsoft.AspNetCore.Routing -Version 2.0.1 -ProjectName ClassLib012
Install-Package Microsoft.Extensions.Configuration.Abstractions -Version 2.0.0 -ProjectName ClassLib012
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib012
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib012
Install-Package Microsoft.Extensions.Configuration -Version 2.0.0 -ProjectName ClassLib013
Install-Package Microsoft.Extensions.Configuration.FileExtensions -Version 2.0.0 -ProjectName ClassLib013
Install-Package YamlDotNet -Version 4.2.1 -ProjectName ClassLib013
Install-Package Newtonsoft.Json -Version 10.0.3 -ProjectName ClassLib014
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib015
Install-Package Microsoft.Extensions.FileProviders.Abstractions -Version 2.0.0 -ProjectName ClassLib015
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib015
Install-Package Microsoft.Extensions.Logging.Abstractions -Version 2.0.0 -ProjectName ClassLib015
Install-Package Microsoft.Extensions.Options -Version 2.0.0 -ProjectName ClassLib015
Install-Package Newtonsoft.Json -Version 10.0.3 -ProjectName ClassLib015
Install-Package Microsoft.AspNetCore.Mvc.ViewFeatures -Version 2.0.1 -ProjectName ClassLib016
Install-Package Microsoft.AspNetCore.Razor.Runtime -Version 2.0.1 -ProjectName ClassLib016
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib017
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib017
Install-Package Microsoft.AspNetCore.Identity -Version 2.0.1 -ProjectName ClassLib018
Install-Package Microsoft.AspNetCore.Mvc.Core -Version 2.0.1 -ProjectName ClassLib020
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib020
Install-Package Microsoft.AspNetCore.Mvc.Abstractions -Version 2.0.1 -ProjectName ClassLib021
Install-Package Microsoft.AspNetCore.Mvc.Core -Version 2.0.1 -ProjectName ClassLib021
Install-Package Microsoft.Extensions.Configuration -Version 2.0.0 -ProjectName ClassLib022
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib022
Install-Package Microsoft.Extensions.Logging.Abstractions -Version 2.0.0 -ProjectName ClassLib022
Install-Package Newtonsoft.Json -Version 10.0.3 -ProjectName ClassLib022
Install-Package WindowsAzure.Storage -Version 8.5.0 -ProjectName ClassLib023
Install-Package Microsoft.Extensions.FileProviders.Physical -Version 2.0.0 -ProjectName ClassLib024
Install-Package Microsoft.AspNetCore.Hosting.Abstractions -Version 2.0.1 -ProjectName ClassLib025
Install-Package Microsoft.Extensions.Caching.Abstractions -Version 2.0.0 -ProjectName ClassLib025
Install-Package Microsoft.Extensions.Localization -Version 2.0.1 -ProjectName ClassLib025
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib025
Install-Package Lucene.Net.QueryParser -Version 4.8.0-beta00004 -ProjectName ClassLib026
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib026
Install-Package Newtonsoft.Json -Version 10.0.3 -ProjectName ClassLib026
Install-Package Microsoft.AspNetCore.Mvc.Core -Version 2.0.1 -ProjectName ClassLib028
Install-Package Microsoft.AspNetCore.Mvc.Razor -Version 2.0.1 -ProjectName ClassLib028
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib028
Install-Package System.Collections.Specialized -Version 4.3.0 -ProjectName ClassLib029
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib030
Install-Package Jint -Version 2.11.10 -ProjectName ClassLib031
Install-Package Microsoft.Extensions.Caching.Abstractions -Version 2.0.0 -ProjectName ClassLib031
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib031
Install-Package Microsoft.AspNetCore.Hosting.Abstractions -Version 2.0.1 -ProjectName ClassLib033
Install-Package Microsoft.Extensions.Logging.Abstractions -Version 2.0.0 -ProjectName ClassLib033
Install-Package Microsoft.AspNetCore.Http.Abstractions -Version 2.0.1 -ProjectName ClassLib034
Install-Package Microsoft.Extensions.Logging.Abstractions -Version 2.0.0 -ProjectName ClassLib034
Install-Package Microsoft.AspNetCore.Diagnostics.Elm -Version 0.2.2 -ProjectName ClassLib035
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib036
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib036
Install-Package Microsoft.Extensions.Caching.Abstractions -Version 2.0.0 -ProjectName ClassLib037
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib037
Install-Package Microsoft.Extensions.Options -Version 2.0.0 -ProjectName ClassLib037
Install-Package System.Threading.Tasks.Parallel -Version 4.3.0 -ProjectName ClassLib037
Install-Package Microsoft.Extensions.Configuration.Abstractions -Version 2.0.0 -ProjectName ClassLib038
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib038
Install-Package Microsoft.Extensions.Configuration.Xml -Version 2.0.0 -ProjectName ClassLib038
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib038
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib038
Install-Package Microsoft.Extensions.Logging.Abstractions -Version 2.0.0 -ProjectName ClassLib038
Install-Package Microsoft.Extensions.Options -Version 2.0.0 -ProjectName ClassLib038
Install-Package System.Threading.Tasks.Parallel -Version 4.3.0 -ProjectName ClassLib038
Install-Package Microsoft.AspNetCore.Mvc.Abstractions -Version 2.0.1 -ProjectName ClassLib039
Install-Package NLog.Web.AspNetCore -Version 4.4.1 -ProjectName ClassLib041
Install-Package System.Security.AccessControl -Version 4.4.0 -ProjectName ClassLib041
Install-Package Microsoft.AspNetCore.Mvc -Version 2.0.1 -ProjectName ClassLib042
Install-Package Microsoft.AspNetCore.Routing -Version 2.0.1 -ProjectName ClassLib042
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib042
Install-Package Microsoft.Extensions.FileProviders.Abstractions -Version 2.0.0 -ProjectName ClassLib042
Install-Package Microsoft.Extensions.FileProviders.Physical -Version 2.0.0 -ProjectName ClassLib042
Install-Package Microsoft.Extensions.Logging.Abstractions -Version 2.0.0 -ProjectName ClassLib042
Install-Package Microsoft.AspNetCore.Hosting.Abstractions -Version 2.0.1 -ProjectName ClassLib043
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib043
Install-Package Microsoft.Extensions.FileSystemGlobbing -Version 2.0.0 -ProjectName ClassLib043
Install-Package Microsoft.AspNetCore.ResponseCaching -Version 2.0.1 -ProjectName ClassLib044
Install-Package Microsoft.AspNetCore.Authorization -Version 2.0.1 -ProjectName ClassLib045
Install-Package Microsoft.AspNetCore.Identity -Version 2.0.1 -ProjectName ClassLib047
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib047
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib047
Install-Package YesSql.Core -Version 2.0.0-beta-1097 -ProjectName ClassLib047
Install-Package Microsoft.AspNetCore.Mvc.Formatters.Xml -Version 2.0.1 -ProjectName ClassLib048
Install-Package Microsoft.AspNetCore.Mvc.ViewFeatures -Version 2.0.1 -ProjectName ClassLib048
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib048
Install-Package Microsoft.AspNetCore.Html.Abstractions -Version 2.0.0 -ProjectName ClassLib049
Install-Package Microsoft.AspNetCore.Routing.Abstractions -Version 2.0.1 -ProjectName ClassLib049
Install-Package Newtonsoft.Json -Version 10.0.3 -ProjectName ClassLib049
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib050
Install-Package Microsoft.Extensions.Logging.Abstractions -Version 2.0.0 -ProjectName ClassLib050
Install-Package Newtonsoft.Json -Version 10.0.3 -ProjectName ClassLib050
Install-Package YesSql.Provider.MySql -Version 1.0.0-beta-1097 -ProjectName ClassLib050
Install-Package YesSql.Provider.PostgreSql -Version 1.0.0-beta-1097 -ProjectName ClassLib050
Install-Package YesSql.Provider.SqLite -Version 1.0.0-beta-1097 -ProjectName ClassLib050
Install-Package YesSql.Provider.SqlServer -Version 1.0.0-beta-1097 -ProjectName ClassLib050
Install-Package Castle.Core -Version 4.1.1 -ProjectName ClassLib051
Install-Package Microsoft.AspNetCore.Html.Abstractions -Version 2.0.0 -ProjectName ClassLib051
Install-Package Microsoft.AspNetCore.Mvc.Localization -Version 2.0.1 -ProjectName ClassLib051
Install-Package Microsoft.Extensions.Logging.Abstractions -Version 2.0.0 -ProjectName ClassLib051
Install-Package System.Diagnostics.TraceSource -Version 4.3.0 -ProjectName ClassLib051
Install-Package System.Reflection.Extensions -Version 4.3.0 -ProjectName ClassLib051
Install-Package Microsoft.AspNetCore.Mvc.Core -Version 2.0.1 -ProjectName ClassLib052
Install-Package Microsoft.AspNetCore.Mvc.ViewFeatures -Version 2.0.1 -ProjectName ClassLib052
Install-Package Microsoft.AspNetCore.Routing -Version 2.0.1 -ProjectName ClassLib052
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib054
Install-Package Microsoft.AspNetCore.Hosting -Version 2.0.1 -ProjectName ClassLib055
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib055
Install-Package Microsoft.AspNetCore.Hosting.Abstractions -Version 2.0.1 -ProjectName ClassLib056
Install-Package Microsoft.AspNetCore.Http -Version 2.0.1 -ProjectName ClassLib056
Install-Package Microsoft.AspNetCore.StaticFiles -Version 2.0.1 -ProjectName ClassLib056
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib056
Install-Package Microsoft.Extensions.FileProviders.Composite -Version 2.0.0 -ProjectName ClassLib056
Install-Package Microsoft.Extensions.Localization -Version 2.0.1 -ProjectName ClassLib056
Install-Package Microsoft.Extensions.Logging -Version 2.0.0 -ProjectName ClassLib056
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib058
Install-Package Microsoft.AspNetCore.Html.Abstractions -Version 2.0.0 -ProjectName ClassLib059
Install-Package Microsoft.AspNetCore.Mvc.DataAnnotations -Version 2.0.1 -ProjectName ClassLib059
Install-Package Microsoft.AspNetCore.Mvc.ViewFeatures -Version 2.0.1 -ProjectName ClassLib059
Install-Package Microsoft.Extensions.Caching.Abstractions -Version 2.0.0 -ProjectName ClassLib059
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib061
Install-Package Microsoft.AspNetCore.Diagnostics -Version 2.0.1 -ProjectName ClassLib062
Install-Package Microsoft.AspNetCore.Mvc.ViewFeatures -Version 2.0.1 -ProjectName ClassLib062
Install-Package Microsoft.AspNetCore.StaticFiles -Version 2.0.1 -ProjectName ClassLib062
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib062
Install-Package Microsoft.AspNetCore.Http.Abstractions -Version 2.0.1 -ProjectName ClassLib065
Install-Package Microsoft.Extensions.Caching.Abstractions -Version 2.0.0 -ProjectName ClassLib065
Install-Package Microsoft.Extensions.Caching.Memory -Version 2.0.0 -ProjectName ClassLib065
Install-Package Microsoft.AspNetCore.Mvc.Abstractions -Version 2.0.1 -ProjectName ClassLib066
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib066
Install-Package Microsoft.AspNetCore.Owin -Version 2.0.1 -ProjectName ClassLib072
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib072
Install-Package Nancy -Version 2.0.0-clinteastwood -ProjectName ClassLib072
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib073
Install-Package Microsoft.AspNetCore.Identity -Version 2.0.1 -ProjectName ClassLib074
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib074
Install-Package Microsoft.AspNetCore.Mvc -Version 2.0.1 -ProjectName ClassLib075
Install-Package Microsoft.Extensions.Caching.Abstractions -Version 2.0.0 -ProjectName ClassLib075
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib075
Install-Package Microsoft.AspNetCore.Identity -Version 2.0.1 -ProjectName ClassLib076
Install-Package Microsoft.AspNetCore.StaticFiles -Version 2.0.1 -ProjectName ClassLib077
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib077
Install-Package Microsoft.AspNetCore.Mvc -Version 2.0.1 -ProjectName ClassLib078
Install-Package Microsoft.AspNetCore.Mvc.TagHelpers -Version 2.0.1 -ProjectName ClassLib078
Install-Package Microsoft.AspNetCore.Mvc -Version 2.0.1 -ProjectName ClassLib079
Install-Package Microsoft.AspNetCore.Mvc.TagHelpers -Version 2.0.1 -ProjectName ClassLib079
Install-Package Microsoft.AspNetCore.Mvc -Version 2.0.1 -ProjectName ClassLib080
Install-Package Microsoft.AspNetCore.Mvc.TagHelpers -Version 2.0.1 -ProjectName ClassLib080
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib081
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib083
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib084
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib085
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib086
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib087
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib091
Install-Package Nancy -Version 2.0.0-clinteastwood -ProjectName ClassLib093
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib094
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib095
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib096
Install-Package Microsoft.AspNetCore.Identity -Version 2.0.1 -ProjectName ClassLib097
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib097
Install-Package Microsoft.AspNetCore.Mvc -Version 2.0.1 -ProjectName ClassLib098
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib098
Install-Package Microsoft.AspNetCore.Mvc -Version 2.0.1 -ProjectName ClassLib099
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib099
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib100
Install-Package Microsoft.AspNetCore.Mvc -Version 2.0.1 -ProjectName ClassLib104
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib104
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib105
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib106
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib108
Install-Package System.IO.Compression.ZipFile -Version 4.3.0 -ProjectName ClassLib108
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib109
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib111
Install-Package Fluid.Core -Version 1.0.0-beta-9399 -ProjectName ClassLib112
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib112
Install-Package Microsoft.AspNetCore.Mvc.Localization -Version 2.0.1 -ProjectName ClassLib113
Install-Package Lucene.Net.Analysis.Common -Version 4.8.0-beta00004 -ProjectName ClassLib114
Install-Package Lucene.Net.QueryParser -Version 4.8.0-beta00004 -ProjectName ClassLib114
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib114
Install-Package Markdig -Version 0.13.1 -ProjectName ClassLib115
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib115
Install-Package Microsoft.AspNetCore.Mvc.TagHelpers -Version 2.0.1 -ProjectName ClassLib116
Install-Package Microsoft.AspNetCore.Mvc.ViewFeatures -Version 2.0.1 -ProjectName ClassLib116
Install-Package Microsoft.AspNetCore.StaticFiles -Version 2.0.1 -ProjectName ClassLib116
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib116
Install-Package MimeMapping -Version 1.0.1.10 -ProjectName ClassLib116
Install-Package OrchardCore.ImageSharp.Web -Version 1.0.0-ci0027 -ProjectName ClassLib116
Install-Package Microsoft.AspNetCore -Version 2.0.1 -ProjectName ClassLib117
Install-Package Microsoft.AspNetCore.Diagnostics -Version 2.0.1 -ProjectName ClassLib117
Install-Package Microsoft.AspNetCore.Mvc.ViewFeatures -Version 2.0.1 -ProjectName ClassLib117
Install-Package Microsoft.AspNetCore.Server.IISIntegration -Version 2.0.1 -ProjectName ClassLib117
Install-Package Microsoft.AspNetCore.Server.Kestrel -Version 2.0.1 -ProjectName ClassLib117
Install-Package Microsoft.AspNetCore.StaticFiles -Version 2.0.1 -ProjectName ClassLib117
Install-Package Microsoft.Extensions.Localization.Abstractions -Version 2.0.1 -ProjectName ClassLib117
Install-Package Microsoft.Extensions.Logging.Console -Version 2.0.0 -ProjectName ClassLib117
Install-Package System.Collections.Specialized -Version 4.3.0 -ProjectName ClassLib117
Install-Package System.Dynamic.Runtime -Version 4.3.0 -ProjectName ClassLib117
Install-Package System.Linq -Version 4.3.0 -ProjectName ClassLib117
Install-Package AspNet.Security.OAuth.Validation -Version 2.0.0-rc1-0286 -ProjectName ClassLib118
Install-Package Microsoft.AspNetCore.Authentication.JwtBearer -Version 2.0.1 -ProjectName ClassLib118
Install-Package OpenIddict -Version 2.0.0-preview1-0657 -ProjectName ClassLib118
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib120
Install-Package Microsoft.Extensions.Localization -Version 2.0.1 -ProjectName ClassLib120
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib122
Install-Package Microsoft.Extensions.Configuration.Json -Version 2.0.0 -ProjectName ClassLib123
Install-Package Microsoft.AspNetCore -Version 2.0.1 -ProjectName ClassLib125
Install-Package Microsoft.AspNetCore.Diagnostics -Version 2.0.1 -ProjectName ClassLib125
Install-Package Microsoft.AspNetCore.Server.IISIntegration -Version 2.0.1 -ProjectName ClassLib125
Install-Package Microsoft.AspNetCore.Server.Kestrel -Version 2.0.1 -ProjectName ClassLib125
Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 2.0.0 -ProjectName ClassLib125
Install-Package Microsoft.Extensions.Logging.Console -Version 2.0.0 -ProjectName ClassLib125
Install-Package System.Collections.Specialized -Version 4.3.0 -ProjectName ClassLib125
Install-Package System.Dynamic.Runtime -Version 4.3.0 -ProjectName ClassLib125
Install-Package System.Linq -Version 4.3.0 -ProjectName ClassLib125
Install-Package Irony.Core -Version 1.0.7 -ProjectName ClassLib126
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib126
Install-Package Microsoft.Extensions.DependencyInjection -Version 2.0.0 -ProjectName ClassLib128
Install-Package Microsoft.NET.Test.Sdk -Version 15.3.0 -ProjectName ClassLib128
Install-Package Moq -Version 4.7.99 -ProjectName ClassLib128
Install-Package xunit -Version 2.3.0-beta2-build3683 -ProjectName ClassLib128
Install-Package xunit.analyzers -Version 0.3.0 -ProjectName ClassLib128
Install-Package xunit.runner.visualstudio -Version 2.3.0-beta2-build1317 -ProjectName ClassLib128
